### ISSUE TITLE
Warning when inheriting from interface

### ISSUE THREAD

**Issue by JakobChristensen** [bkoelman/ResharperCodeContractNullability#5]
Hi

Great analyzer!

If I have an interface and two classes like this:

![image](https://cloud.githubusercontent.com/assets/2310296/10038728/e9421afc-61c9-11e5-9358-c2fe1c94a2fb.png)

I get an error that "text" is not decorated in Derrived.Foo().

**Comment by bkoelman** [comment]
Hi Jakob, thanks for taking the time to report this.

A [similar issue](https://github.com/bkoelman/ResharperCodeContractNullability/issues/3) was fixed in [v1.0.2](https://github.com/bkoelman/ResharperCodeContractNullability/releases/tag/v1.0.2) a few days ago. Can you verify if that fixes the problem for you?

The thing is, I cannot reproduce the problem in the latest version...

![image](https://cloud.githubusercontent.com/assets/10324372/10041652/e8767598-61e5-11e5-8a5c-4ffc54bb25f7.png)

**Comment by JakobChristensen** [comment]
Hi Bart

Yep – that solved it!

Thought I was running on 1.0.2, but apparently not – probably did not restart Visual Studio.

Thanks for the help!

--Jakob

**Comment by starkcolin** [comment]
I still experience this error on 1.0.3 in the following situation, similar to the original bug report but in the specific scenario of: Concrete Class derives from Generic Class implements Generic Interface:

![image](https://cloud.githubusercontent.com/assets/9094377/12129904/94cc638a-b3d4-11e5-83e8-af5aa67c394e.png)

The error is "Parameter 'text' is missing nullability annotation."
